/*
    Matthew Ivezaj
    May 17, 2022
    Divisible by three
*/
//Importing Scanner.
import java.util.Scanner;
//Creating a public class.
public class DivisibleByThree {
    //Creating a mean method.
    public static void main(String[] args) 
    {
        //Creating a scanner object.
        Scanner keyboard = new Scanner(System.in);
       //Asking the user to enter an integer. 
       System.out.println("Please enter an integer:\t");
       //Allowing the user to input an answer.
       userInput = keyboard.nextInt();
       //Creating a switch statement.
    }
}